### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by trenlies** [matteozappia/Sonic-Bug-Tracker#14]
**Describe the Bug**
Im trying to create a ringtone, but it doesnt work. Im doing all the tutorial that you post. The ringtone doesnt add then to iPhone settings sound. I need a solution.

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.
![34B89349-F44C-4ABF-9548-7FF304AC48B9](https://user-images.githubusercontent.com/48494669/89778824-c669d280-dad3-11ea-839f-6ab0a7a70dd5.png)
![82C02F6C-0124-4EC3-96A7-5228AAE880D2](https://user-images.githubusercontent.com/48494669/89778834-c964c300-dad3-11ea-95e4-aff1f4cb86c8.png)

**Info (please complete the following informations):**
 - Device: iPhone 6S
 - iOS: 13.6
 - Jailbreak: Checkra1n 
 - Sonic Version: 1.0

**Additional context**

**Comment by matteozappia** [comment]
you need to update to Sonic 1.2! This bug was fixed.
