### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by c0sm0s01** [matteozappia/Sonic-Bug-Tracker#15]
**Describe the bug**
After i had downloaded the song of choice, trim and saved it, the ringtone does not appear in the settings.

**Screenshots or Videos**
NA

**Info (please complete the following informations):**
 - Device: IPhone 8
 - iOS: 13.5
 - Jailbreak: uncover 
 - Sonic Version: 1.2

**Additional context**

**Comment by matteozappia** [comment]
try to delete the Sonic Media folder (/var/mobile/Media/Sonic) then uninstall Sonic and ToneEnabler13 and install them again.
