### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by trenlies** [matteozappia/Sonic-Bug-Tracker#16]
**Describe the Bug**
I already updated the tweak to 1.2 and still the same, it doesnt add the ringtones to audio settings, please, could u really fix it??

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.

**Info (please complete the following informations):**
 - Device: iPhone 6S
 - iOS: 13.6
 - Jailbreak: Checkra1n
 - Sonic Version: 1.2

**Additional context**

**Comment by matteozappia** [comment]
It's fixed. just check to delete the Sonic Media folder (/var/mobile/Media/Sonic) then uninstall Sonic and ToneEnabler13 and then reinstall them.

**Comment by trenlies** [comment]
Ok, it works, thanks, Greta tweak!!!

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Matteo Zappia <notifications@github.com>
Enviado: Monday, August 10, 2020 10:59:15 AM
Para: matteozappia/Sonic-Bug-Tracker <Sonic-Bug-Tracker@noreply.github.com>
Cc: trenlies <luvlies1981@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [matteozappia/Sonic-Bug-Tracker] [BUG] (#16)


It's fixed. just check to delete the Sonic Media folder (/var/mobile/Media/Sonic) then uninstall Sonic and ToneEnabler13 and then reinstall them.
