### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xiaosi0105** [matteozappia/Sonic-Bug-Tracker#17]
**Describe the Bug**
Can’t cut .m4a 
![0DBA3E11-1192-4744-9644-A54EE008E134](https://user-images.githubusercontent.com/50315853/89854760-50df2e80-dbc7-11ea-8085-d338c7f99ed0.png)

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.

**Info (please complete the following informations):**
 - Device: [e.g. iPhone X]iPhone X
 - iOS: [e.g. 13.5.1] 13.5
 - Jailbreak: [e.g. checkra1n] unc0ver
 - Sonic Version: [e.g. 1.0] 1.2

**Additional context**
m4a can’t edit or play plz fix it thx

**Comment by matteozappia** [comment]
Hey! At the moment you have to cut even a small part, but you must do it otherwise the Done button won't became touchable. It's not a bug, but i'll introduce in the next update the ability to tap on Done button without cutting the audio.
