### ISSUE TITLE
Cannot Delete Ringtones [BUG]

### ISSUE THREAD

**Issue by taqikazmi123** [matteozappia/Sonic-Bug-Tracker#19]
#**Describe the Bug**

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.

**Info (please complete the following informations):**
 - Device: iPhone 7 Plus
 - iOS: 13.5
 - Jailbreak: Unc0ver
 - Sonic Version: 1.2

**Additional context**

**Comment by matteozappia** [comment]
It happens because you've used an old Sonic version before 1.2, if you can't delete a ringtone from Sonic delete it from Filza. Btw i fixed that bug in 1.3, it will be out soon!
