### ISSUE TITLE
[BUG]Not Working iOS 14.3 iPhone 12 Pro Max

### ISSUE THREAD

**Issue by danternero** [matteozappia/Sonic-Bug-Tracker#29]
**Describe the Bug**
After Select a file all button arent allow to use that's mean I can't create any ringtone.
**Screenshots or Videos**
If applicable
![28853BC1-7B74-491C-9E50-51D3B6055973](https://user-images.githubusercontent.com/81539364/112772995-3b3b4e00-905e-11eb-803f-953d899bf5b1.png)
, add screenshots or videos to help explain your problem.

**Info (please complete the following informations):**
 - Device: iPhone 12 Pro Max
 - iOS: 14.3RC
 - Jailbreak: Uncover 6.1.1
 - Sonic Version: 1.4

**Additional context**
I'm already installed ToneEnabler 13 , it not work is there any update for iOS 14 ? Plz help

**Comment by matteozappia** [comment]
This is not a bug, you have to cut the ringtone at the moment then you can save it. And please do not report multiple times the same "bug". Thanks!
